#!/bin/bash

if [[ ! ${1+x} ]]; then
    vim ~/Documents/TODO.md
elif [ $1 == "infos" ]; then
    echo -e "\e[1m\e[91mÀ faire :\e[0m";
    cat ~/Documents/TODO.md | grep --color=never -F "[ ]";
    echo -e "\n\e[1m\e[32mFait :\e[0m";
    cat ~/Documents/TODO.md | grep --color=never -F "[x]";
else
    "$1" ~/Documents/TODO.md
fi

